platform :ios, '9.0'
use_frameworks!

target 'WRSwiftUtilDemo' do

    pod 'Colours'
    pod 'MBProgressHUD'
    pod 'NVActivityIndicatorView', '~> 4.1.1'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
